//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

namespace serwisSpolecznosciowy {
    using System;
    
    
    /// <summary>
    ///   Klasa zasobu wymagająca zdefiniowania typu do wyszukiwania zlokalizowanych ciągów itd.
    /// </summary>
    // Ta klasa została automatycznie wygenerowana za pomocą klasy StronglyTypedResourceBuilder
    // przez narzędzie, takie jak ResGen lub Visual Studio.
    // Aby dodać lub usunąć członka, edytuj plik .ResX, a następnie ponownie uruchom ResGen
    // z opcją /str lub ponownie utwórz projekt VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MyLanguageResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MyLanguageResources() {
        }
        
        /// <summary>
        /// Zwraca buforowane wystąpienie ResourceManager używane przez tę klasę.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("serwisSpolecznosciowy.MyLanguageResources", typeof(MyLanguageResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Przesłania właściwość CurrentUICulture bieżącego wątku dla wszystkich
        ///   przypadków przeszukiwania zasobów za pomocą tej klasy zasobów wymagającej zdefiniowania typu.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Some exemplary logins have already existed..
        /// </summary>
        public static string ErrorCannotInit {
            get {
                return ResourceManager.GetString("ErrorCannotInit", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Admin cannot be removed..
        /// </summary>
        public static string ErrorDeleteAdmin {
            get {
                return ResourceManager.GetString("ErrorDeleteAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Login input is empty..
        /// </summary>
        public static string ErrorEmptyLoginInput {
            get {
                return ResourceManager.GetString("ErrorEmptyLoginInput", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu You cannot add yourself..
        /// </summary>
        public static string ErrorFriendAddYourself {
            get {
                return ResourceManager.GetString("ErrorFriendAddYourself", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu You cannot delete yourself..
        /// </summary>
        public static string ErrorFriendDelYourself {
            get {
                return ResourceManager.GetString("ErrorFriendDelYourself", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu User doesnt have friend with that login..
        /// </summary>
        public static string ErrorFriendDoesntExist {
            get {
                return ResourceManager.GetString("ErrorFriendDoesntExist", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu User has friend with that login..
        /// </summary>
        public static string ErrorFriendExists {
            get {
                return ResourceManager.GetString("ErrorFriendExists", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Wrong file was chosen..
        /// </summary>
        public static string ErrorImportWrongFile {
            get {
                return ResourceManager.GetString("ErrorImportWrongFile", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu User with that login doesnt exist..
        /// </summary>
        public static string ErrorUserDoesntExist {
            get {
                return ResourceManager.GetString("ErrorUserDoesntExist", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu User with that login exists..
        /// </summary>
        public static string ErrorUserExists {
            get {
                return ResourceManager.GetString("ErrorUserExists", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Successfully added friend..
        /// </summary>
        public static string SuccessFriendAdded {
            get {
                return ResourceManager.GetString("SuccessFriendAdded", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Successfully deleted friend..
        /// </summary>
        public static string SuccessFriendDeleted {
            get {
                return ResourceManager.GetString("SuccessFriendDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Successfully imported friends..
        /// </summary>
        public static string SuccessImportFriends {
            get {
                return ResourceManager.GetString("SuccessImportFriends", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Successfully added exemplary users..
        /// </summary>
        public static string SuccessInitDone {
            get {
                return ResourceManager.GetString("SuccessInitDone", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Successfully added user..
        /// </summary>
        public static string SuccessUserAdded {
            get {
                return ResourceManager.GetString("SuccessUserAdded", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Successfully deleted user..
        /// </summary>
        public static string SuccessUserDeleted {
            get {
                return ResourceManager.GetString("SuccessUserDeleted", resourceCulture);
            }
        }
    }
}
